### ISSUE TITLE
[BUG] `all shards failed` error con CM's SearchThread 

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-indexer-plugins#167] opened 2024-12-05 12:53 UTC
**Describe the bug**
During the testing of the latest package of Wazuh Indexer, the CM reports the following error.

**To Reproduce**
- Install the package
- Start and initialize the indexer.
- Check the logs

**Expected behavior**
No error is raised.

**Plugins**
Command Manager plugin.

**Screenshots**
```log
[2024-12-05T11:49:54,046][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:50:54,048][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:51:54,045][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:52:54,045][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:53:54,058][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:54:54,054][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:56:54,056][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
[2024-12-05T11:57:54,063][ERROR][c.w.c.j.SearchThread     ] [node-1] Generic exception retrieving page: all shards failed
```

**Host/Environment (please complete the following information):**
 - OS: ['deb', 'rpm']
 - Version ['5.0.0']

**Additional context**
Packages: https://github.com/wazuh/wazuh-indexer/actions/runs/12164433520

**Comment by f-galland** [comment] 2024-12-06 18:35
The issue was caused by the `handlePage()` in combination with the `getNestedObject()` method:

 `getNestedObject()` was retrieving an inner `Object` within a `Map<String,Object>` using `get()` assigning its return to a `Object value`.
This actually passed a reference to the inner object instead of a deep copy.

An updated version of `getNestedObject()` uses the `HashMap<>()` constructor to build a deep copy of the original nested object, which can be modified without worrying about it mangling with the original one.

**Closed by f-galland** 2024-12-06 18:35 UTC
Labels: level/task, type/bug, mvp
